import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../Components/Navbar'
import {Container, Paper, Box} from "@mui/material"
import MaterialUISwitch from '../Components/MaterialUiSwitch'


const Home: NextPage = (props: any) => {
  return (
    <div>
      <Head>
        <title>Next.js dark/light mode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar/>
      </header>

      <Container maxWidth="md">
        <main style={{textAlign: "center"}}>
          <h1>Next.js dark/light mode</h1>
          <MaterialUISwitch checked={props.themeNow === 'dark' ? true : false} onChange={props.toggleTheme}></MaterialUISwitch>

          <Box sx={{display: "flex", flexDirection: "row", justifyContent: "center", alignItems: "center", flexWrap: "wrap", gap: "3em", marginTop: "5em", wordBreak: "break-word"}}>
            <Paper elevation={3} sx={{padding: "1em", maxWidth: "15em"}} >
              <h2>This is a paper</h2>
              <p>It&apos;s living on it&apos;s own it&apos;s doing it&apos;s things you know</p>
            </Paper>
            <Paper elevation={3} sx={{padding: "1em", maxWidth: "15em"}} >
              <h2>This is a paper</h2>
              <p>It&apos;s living on it&apos;s own it&apos;s doing it&apos;s things you know</p>
            </Paper>
            <Paper elevation={3} sx={{padding: "1em", maxWidth: "15em"}} >
              <h2>This is a paper</h2>
              <p>It&apos;s living on it&apos;s own it&apos;s doing it&apos;s things you know</p>
            </Paper>
          </Box>
        </main>
      </Container>
    </div>
  )
}

export default Home
